name: devstore

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Generate localizations
        run: flutter gen-l10n

      - name: Build APK
        run: |
           flutter pub get
           flutter build apk --release --no-pub


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: devstore-apk
          path: build/app/outputs/apk/release/app-release.apk

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Generate localizations
        run: flutter gen-l10n

      - name: Build Web (Admin Panel)
        run: flutter build web --release -t lib/main_admin.dart

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: devstore-web
          path: build/web

  deploy-web:
    needs: build-web
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Web Build
        uses: actions/download-artifact@v4
        with:
          name: devstore-web
          path: build/web

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
